# Generated by Django 5.0.1 on 2024-01-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('subProductId', models.AutoField(primary_key=True, serialize=False)),
                ('subProductName', models.CharField(max_length=255)),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('selectionId', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(to='api.product')),
                ('subCategories', models.ManyToManyField(to='api.subcategory')),
                ('subProducts', models.ManyToManyField(to='api.subproduct')),
            ],
        ),
    ]
